stages:
  - setup
  - test

setup:
  stage: setup
  script:
    - npm install

test:
  stage: test
  script:
    - npm run init
    - npm test

cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/
